### ISSUE TITLE
Updating to Flask 2.0 / Werkzeug 2.0 causes a deprecation warning in Flask-Login for safe_str_cmp

### ISSUE THREAD

**Issue by nickjj** [maxcountryman/flask-login#584]
**Describe the bug**

Updating to Flask 2.0 / Werkzeug 2.0 causes a deprecation warning for `safe_str_cmp`'s import path.

**To Reproduce**

1. Install Flask 2.0 / Werkzeug 2.0
2. Install Flask-Login 0.5.0
3. Use Flask-Login as per the guide's recommendation
4. See the following warning:

```
python3.9/site-packages/flask_login/utils.py:63: DeprecationWarning: 'safe_str_cmp' is deprecated and will be removed in Werkzeug 2.1. Use 'hmac.compare_digest' instead.
    if safe_str_cmp(_cookie_digest(payload, key=key), digest):
```

**Expected behavior**

No warnings.

**Comment by maxcountryman** [comment]
Thanks for reporting this. Seems like it should be a straightforward fix.

**Comment by davidism** [comment]
Just to reiterate what the warning says since it scrolled off screen: this should be replaced with `hmac.compare_digest`.

**Comment by nickjj** [comment]
Want me to open a PR to address it?

**Comment by maxcountryman** [comment]
We'd be happy to accept a PR if you'd like to put that together.

**Comment by nickjj** [comment]
Ok, I opened a PR at https://github.com/maxcountryman/flask-login/pull/585. I didn't run the test suite locally, but let's see how straightforward this change is haha.

**Comment by le717** [comment]
This has been fixed by #585 and can be closed. :D

**Comment by Augustin-FL** [comment]
Hi @nickjj,
Could you please re-open this?

The issue is not yet fixed : your PR was merged but no new release/tag has yet been set on the project, and pypi was not updated.
Few hours ago, Werkzeug v2.1.0 got released, removing `safe_str_cmp` entirely and causing `flask-login` to break.

Is it possible to let this issue open until pypi repos are fixed?

**Comment by Augustin-FL** [comment]
see also : https://stackoverflow.com/questions/71652965/importerror-cannot-import-name-safe-str-cmp-from-werkzeug-security
